name: GiantBanks
main: nl.giantit.minecraft.GiantBanks.GiantBanks
version: 0.2.DEV
authors: [Giant]
commands:
    bank:
        description: Your private banker!
        aliases: [b]
        usage: /bank [params]
    bl:
        description: This will enable you to make bank locations!
        aliases: [bankloc, l, bl]
        usage: /bl [params]
permissions:
    giantbanks.*:
        description: Gives access to all GiantBanks permissions
        children:
            giantbanks.bank.have: true
            giantbanks.bank.store: true
            giantbanks.bank.get: true
            giantbanks.bank.getall: true
            giantbanks.admin.sendhelp: true
            giantbanks.admin.type.create: true
            giantbanks.admin.type.remove: true
            giantbanks.admin.type.select: true
            giantbanks.admin.type.set: true
            giantbanks.admin.type.storable: true
            giantbanks.admin.account.select: true
            giantbanks.admin.account.clear: true
            giantbanks.admin.account.settype: true
            giantbanks.admin.account.has: true
            giantbanks.admin.account.remove: true
            giantbanks.location.access: true
            giantbanks.location.create: true
            giantbanks.location.remove: true
            giantbanks.location.list: true
    giantbanks.bank.*:
        description: Gives access to the GiantBanks front end
        children:
            giantbanks.bank.have: true
            giantbanks.bank.store: true
            giantbanks.bank.get: true
            giantbanks.bank.getall: true
    giantbanks.admin.*:
        description: Gives access to all GiantBanks admin commands
        children:
            giantbanks.admin.sendhelp: true
            giantbanks.admin.type.create: true
            giantbanks.admin.type.remove: true
            giantbanks.admin.type.select: true
            giantbanks.admin.type.set: true
            giantbanks.admin.type.storable: true
            giantbanks.admin.account.select: true
            giantbanks.admin.account.clear: true
            giantbanks.admin.account.settype: true
            giantbanks.admin.account.has: true
            giantbanks.admin.account.remove: true
    giantbanks.location.*:
        description: Gives access to all GiantBanksLocation commands
        children:
            giantbanks.location.access: true
            giantbanks.location.create: true
            giantbanks.location.remove: true
            giantbanks.location.list: true
    giantbanks.bank.have:
        description: Gives access to the have command
        default: false
    giantbanks.bank.store:
        description: Gives access to the store command
        default: false
    giantbanks.bank.get:
        description: Gives access to the get command
        default: false
    giantbanks.bank.getall:
        description: Gives access to the get all command
        default: false
    giantbanks.admin.sendhelp:
        description: Enables admin to send GiantBanks help to user
        default: false
    giantbanks.admin.type.create:
        description: Enables admin to create account types
        default: false
    giantbanks.admin.type.remove:
        description: Enables admin to remove account types
        default: false
    giantbanks.admin.type.select:
        description: Enables admin to select account types
        default: false
    giantbanks.admin.type.set:
        description: Enables admin to modify account types
        default: false
    giantbanks.admin.type.storable:
        description: Enables admin to change storable items for account types
        default: false
    giantbanks.admin.account.select:
        description: Enables admin to select user accounts
        default: false
    giantbanks.admin.account.clear:
        description: Enables admin to erase all items from user account
        default: false
    giantbanks.admin.account.settype:
        description: Enables admin to change account type for user account
        default: false
    giantbanks.admin.account.has:
        description: Enables admin to see items from user account
        default: false
    giantbanks.admin.account.remove:
        description: Enables admin to remove accounts from GiantBanks
        default: false
    giantbanks.location.overide:
        description: Enables admin to override location
        default: false
    giantbanks.location.access:
        description: Enables admin to use location plugin
        default: false
    giantbanks.location.create:
        description: Enables admin to create shop
        default: false
    giantbanks.location.remove:
        description: Enables admin to remove shop
        default: false
    giantbanks.location.list:
        description: Enables admin to list available shops
        default: false