name: GiantBanks
main: nl.giantit.minecraft.GiantBanks.GiantBanks
version: 0.1.DEV
commands:
    bank:
        description: Your private banker!
        aliases: [b]
        usage: /bank [params]
    bl:
        description: This will enable you to make bank locations!
        aliases: [bankloc, l, bl]
        usage: /bl [params]
permissions:
    giantbanks.*:
        description: Gives access to all GiantBanks permissions
        children:
            giantbanks.shop.buy: true
            giantbanks.shop.sell: true
            giantbanks.shop.gift: true
            giantbanks.shop.list: true
            giantbanks.shop.check: true
            giantbanks.shop.search: true
            giantbanks.admin.send: true
            giantbanks.admin.add: true
            giantbanks.admin.update: true
            giantbanks.admin.remove: true
            giantbanks.location.access: true
            giantbanks.location.create: true
            giantbanks.location.remove: true
            giantbanks.location.list: true
    giantbanks.shop.*:
        description: Gives access to the GiantBanks payout
        children:
            giantbanks.shop.access: true
            giantbanks.shop.buy: true
            giantbanks.shop.sell: true
            giantbanks.shop.gift: true
            giantbanks.shop.list: true
            giantbanks.shop.check: true
            giantbanks.shop.search: true
    giantbanks.admin.*:
        description: Gives access to all GiantBanks admin commands
        children:
            giantbanks.admin.sendhelp: true
            giantbanks.admin.add: true
            giantbanks.admin.update: true
            giantbanks.admin.remove: true
    giantbanks.location.*:
        description: Gives access to all GiantBanksLocation commands
        children:
            giantbanks.location.access: true
            giantbanks.location.create: true
            giantbanks.location.remove: true
            giantbanks.location.list: true
    giantbanks.shop.buy:
        description: Gives access to the buying feature
        default: true
    giantbanks.shop.sell:
        description: Gives access to the selling feature
        default: true
    giantbanks.shop.gift:
        description: Gives access to the gifting feature
        default: true
    giantbanks.shop.list:
        description: Gives access to the item list feature
        default: true
    giantbanks.shop.check:
        description: Gives access to the item checking feature
        default: true
    giantbanks.shop.search:
        description: Gives access to the item searching feature
        default: true
    giantbanks.admin.sendhelp:
        description: Enables admin to send GiantShop help to user
        default: op
    giantbanks.admin.add:
        description: Enables admin to add items to GiantShop
        default: op
    giantbanks.admin.update:
        description: Enables admin to update items in GiantShop
        default: op
    giantbanks.admin.remove:
        description: Enables admin to remove items from GiantShop
        default: op
    giantbanks.location.overide:
        description: Enables admin to override location
        default: op
    giantbanks.location.access:
        description: Enables admin to use location plugin
        default: op
    giantbanks.location.create:
        description: Enables admin to create shop
        default: op
    giantbanks.location.remove:
        description: Enables admin to remove shop
        default: op
    giantbanks.location.list:
        description: Enables admin to list available shops
        default: op